[tool.poetry]
name = "msc_tests_examples"
version = "0.1.0"
description = ""
authors = ["Guilherme Palazzo <palazzoeng1@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7.*"

# GENERAL MAJOR DEPS
scipy = "1.4.*"
pulp = "2.1"
